[paths]
# examples
# logs = "/your/logs"
# data = "/your/data"
# analysis = "/your/analysis"
#main = "/home/boittier/Documents/github/JaxPycharmm"
# pycharmm = "/your/pycharmm"
# md = "/your/md"
# /Users/ericboittier/Documents/github/JaxPycharmm/paths.toml
